import type { HotelListing } from "@/@types/hotel";

export const HOTEL_CATEGORIES = ['Family', 'Students', 'Travelers'] as const;

export const HOTEL_LOCATIONS = [
  'San José',
  'Heredia',
  'Alajuela',
  'Cartago',
  'Puntarenas',
  'Guanacaste',
  'Limón',
] as const;

export const STUB_HOTELS: HotelListing[] = [
  {
    id: "1",
    name: "La sabana sur",
    address: "329 Calle santos, paseo colón, San José",
    coordinates: { lat: 9.9281, lng: -84.0907 },
    price: 4058,
    bedrooms: 2,
    bathrooms: 1,
    petFriendly: true,
    promoted: true,
    images: [
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
    ],
    category: "Family",
    location: "San José",
    owner: { name: "Alberto Casas", avatar: "/img/person.jpg" },
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    favorite: false,
    rating: 4.9,
  },
  {
    id: "2",
    name: "Los yoses",
    address: "329 Calle santos, paseo colón, San José",
    coordinates: { lat: 9.9366, lng: -84.0703 },
    price: 4000,
    bedrooms: 2,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: [
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
    ],
    category: "Students",
    location: "San José",
    owner: { name: "Alberto Casas", avatar: "/img/person.jpg" },
    description:
      "Compact apartment near key routes with bright interiors and fast access to the city center.",
    favorite: false,
    rating: 4.6,
  },
  {
    id: "3",
    name: "Paseo Colón Loft",
    address: "225 Avenida central, paseo colón, San José",
    coordinates: { lat: 9.9362, lng: -84.1024 },
    price: 3980,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: [
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
    ],
    category: "Travelers",
    location: "San José",
    owner: { name: "Randall Valenciano", avatar: "/img/person.jpg" },
    description:
      "Loft-style living with clean finishes, natural light, and walkable access to major amenities.",
    favorite: true,
    rating: 4.8,
  },
  {
    id: "4",
    name: "Heredia Central",
    address: "101 Calle norte, Heredia centro, Heredia",
    coordinates: { lat: 9.9982, lng: -84.1198 },
    price: 4120,
    bedrooms: 3,
    bathrooms: 2,
    petFriendly: true,
    promoted: true,
    images: [
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
    ],
    category: "Family",
    location: "Heredia",
    owner: { name: "María López", avatar: "/img/person.jpg" },
    description:
      "Larger family-ready floor plan with flexible living space and strong natural ventilation.",
    favorite: false,
    rating: 4.9,
  },
  {
    id: "5",
    name: "Alajuela Heights",
    address: "78 Ruta 3, Alajuela, Alajuela",
    coordinates: { lat: 10.0163, lng: -84.2116 },
    price: 3895,
    bedrooms: 2,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: [
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
    ],
    category: "Travelers",
    location: "Alajuela",
    owner: { name: "Luis Salas", avatar: "/img/person.jpg" },
    description:
      "Quiet rental with a warm palette, ideal for medium stays and airport-adjacent access.",
    favorite: true,
    rating: 4.7,
  },
  {
    id: "6",
    name: "Cartago View",
    address: "54 Vista real, Cartago, Cartago",
    coordinates: { lat: 9.8644, lng: -83.9194 },
    price: 4215,
    bedrooms: 3,
    bathrooms: 2,
    petFriendly: true,
    promoted: false,
    images: [
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
      "/img/hotel/hotel1.jpg",
    ],
    category: "Students",
    location: "Cartago",
    owner: { name: "Ana Ruiz", avatar: "/img/person.jpg" },
    description:
      "Balanced shared-living layout with comfortable bedrooms and a practical amenity mix.",
    favorite: false,
    rating: 4.5,
  },
  {
    id: '9',
    name: 'Brisa del Puerto',
    address: 'Calle 3, Barrio El Carmen, Puntarenas',
    price: 91,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: true,
    images: ['/img/listings/9/1.webp', '/img/listings/9/2.webp', '/img/listings/9/3.webp', '/img/listings/9/4.webp'],
    category: 'Travelers',
    location: 'Puntarenas',
    coordinates: { lat: 9.9776, lng: -84.8292 },
    owner: { name: 'María López', avatar: '/img/avatars/maria.webp' },
    description:
      'Wake up near the Puntarenas waterfront, with the ferry terminal, local seafood spots, and the Paseo de los Turistas within walking distance. This compact apartment is an easy base for beach days and coastal connections.',
    favorite: false,
    rating: 4.8,
  },
  {
    id: '10',
    name: 'Casa Guaria, Tamarindo',
    address: 'Calle Cardinal, Tamarindo, Guanacaste',
    price: 164,
    bedrooms: 3,
    bathrooms: 2,
    petFriendly: true,
    promoted: false,
    images: ['/img/listings/10/1.webp', '/img/listings/10/2.webp', '/img/listings/10/3.webp', '/img/listings/10/4.webp'],
    category: 'Family',
    location: 'Guanacaste',
    coordinates: { lat: 10.2993, lng: -85.8396 },
    owner: { name: 'Randall Valenciano', avatar: '/img/avatars/randall.webp' },
    description:
      'A breezy home in Tamarindo with a shaded outdoor dining area, a short ride from the beach and the estuary trails. Families can spread out across three bedrooms and find surf lessons, fruit stands, and restaurants close by.',
    favorite: true,
    rating: 4.9,
  },
  {
    id: '11',
    name: 'Muelle Viejo Apartment',
    address: 'Avenida 2, Barrio Roosevelt, Limón',
    price: 68,
    bedrooms: 2,
    bathrooms: 1,
    petFriendly: true,
    promoted: false,
    images: ['/img/listings/11/1.webp', '/img/listings/11/2.webp', '/img/listings/11/3.webp', '/img/listings/11/4.webp'],
    category: 'Travelers',
    location: 'Limón',
    coordinates: { lat: 9.9917, lng: -83.0361 },
    owner: { name: 'Alberto Casas', avatar: '/img/avatars/alberto.webp' },
    description:
      'This comfortable apartment is close to Limón’s waterfront, the central market, and the city’s Caribbean restaurants. Two bedrooms and a full kitchen suit small groups looking for a convenient base before heading down the coast.',
    favorite: false,
    rating: 4.6,
  },
  {
    id: '12',
    name: 'Puntarenas Campus Room',
    address: 'Calle 7, Barrio El Cocal, Puntarenas',
    price: 43,
    bedrooms: 1,
    bathrooms: 1,
    petFriendly: false,
    promoted: false,
    images: ['/img/listings/12/1.webp', '/img/listings/12/2.webp', '/img/listings/12/3.webp', '/img/listings/12/4.webp'],
    category: 'Students',
    location: 'Puntarenas',
    coordinates: { lat: 9.9823, lng: -84.8238 },
    owner: { name: 'Luis Salas', avatar: '/img/avatars/luis.webp' },
    description:
      'A compact, furnished room in El Cocal with bus stops, inexpensive cafés, and the Puntarenas campus nearby. It is a straightforward choice for a semester stay, field placement, or visiting student.',
    favorite: false,
    rating: 4.5,
  },
];

export const BEDROOM_FILTERS = [
  { label: "All apartments", value: "all" },
  { label: "1 bedroom", value: "1" },
  { label: "2 bedrooms", value: "2" },
  { label: "3 bedrooms", value: "3" },
] as const;

export function getHotelById(id: string) {
  return STUB_HOTELS.find((hotel) => hotel.id === id);
}

export function getSuggestedHotels(activeId: string) {
  return STUB_HOTELS.filter((hotel) => hotel.id !== activeId).slice(0, 5);
}